<?php
/**
 * Plugin Name: WP Power Cache
 * Author: Milap Patel
 * Description: A simple Page/Post cache plugin.
 * Plugin URI: https://patelmilap.wordpress.com/
 * Author URI: https://youtube.com/c/codecanvas
 * Version: 0.1.0
 * Text Domain: wp-power-cache
 * Requires at least: 5.0
 * Requires PHP: 8.0
 */

if ( !defined( 'ABSPATH' ) ) exit;

require_once plugin_dir_path( __FILE__ ) . 'functions.php';
require_once plugin_dir_path( __FILE__ ) . 'wp-lazy-load.php';

if ( ! class_exists( 'WR_Power_Cache' ) ) :
	class WR_Power_Cache {
		private $cacheFolder = 'wp-power-cache';
		private $isFront = false;
		private $isAdmin = false;
		private $currentCacheFile = '';
		protected static $instance = null;
		protected static $startTime = 0;
		protected static $endTime = 0;
		private $isDev = false;
		private $actions = array(
			'clear_cache' => [
				'switch_theme',
				'comment_post',
				'permalink_structure_changed'
			]
		);

		public function __construct() {
			define( 'WRPC_ROOT_DIR', str_replace( '\\', '/', plugin_dir_path( __FILE__ ) ) );
			$this->cacheFolder = isset( $_SERVER['SERVER_NAME'] ) ? md5( $_SERVER['SERVER_NAME'] ) : $this->cacheFolder;
			
			$settings = (array) get_option( 'wp_power_cache_settings' );
			$this->isDev = isset($settings['developer_flag']) && $settings['developer_flag'] == 1;

			if ( ! file_exists( WRPC_ROOT_DIR . $this->cacheFolder ) ) {
				wp_mkdir_p( WRPC_ROOT_DIR . $this->cacheFolder );
				chmod( WRPC_ROOT_DIR . $this->cacheFolder, 0777 );
			}
			$this->add_actions();
		}

		public function get_post_action_handler( $q ) {
			if ( is_admin() ) return;

			// FIX: Get the filename first to check if it exists
			$this->currentCacheFile = $this->get_query_parameters( $q );

			// IF CACHE EXISTS: Do not start the buffer. 
			// This prevents the signature from being added a second time.
			if ( $this->cache_exists() && !is_user_logged_in() ) {
				return;
			}

			if ( $this->validCatchFile() ) {
				ob_start( array( $this, 'end_post_action_handler' ) );
			}
		}

		public function load_cache_action_handler() {
			$this->FrontOrAdmin();
			if ( $this->isFront && $this->cache_exists() ) {
				echo file_get_contents( $this->cache_file_path() );
				$this->end_page_load_time();
				exit;
			}
		}

		public function start_page_load_time() {
			self::$startTime = microtime( true );
		}

		public function end_page_load_time() {
			self::$endTime = microtime( true );
			$finish = round( ( self::$endTime - self::$startTime ), 4 );
			
			// Only show the black bar if Developer Mode is ON
			if ( $this->isDev ) {
				wrpc_print_loading_time( $finish );
			} 
		}

		public function end_post_action_handler( $buffer ) {
			if ( is_404() || empty($buffer) ) {
				return $buffer;
			}

			$settings = (array) get_option( 'wp_power_cache_settings' );
			
			if ( isset($settings['debug_flag']) && $settings['debug_flag'] == 1 ) {
				$finish = round( ( microtime(true) - self::$startTime ), 4 );

				// Generate a short unique ID for this specific cache version
				$cache_id = strtoupper( uniqid() );
				
				$signature .= "<!-- This cached page generated by WP-Power-Cache on ". date( "d-m-Y H:i:s" ) ." -->\n";
				$signature .= "\n";
				
				$buffer .= $signature; 
			}

			return $this->create_cache( $buffer );
		}

		private function validCatchFile() {
			if ( empty($this->currentCacheFile) ) return false;
			$ext = pathinfo( $this->currentCacheFile, PATHINFO_EXTENSION );
			return !in_array( $ext, $this->invalid_file_extensions() );
		}

		private function invalid_file_extensions() {
			return array('gif', 'jpeg', 'jpg', 'png', 'swf', 'psd', 'bmp', 'tiff', 'ico');
		}

		private function get_query_parameters( $q ) {
			return $this->get_standard_filename();
		}

		private function add_actions() {
			// 1. CLEARING MUST BE FIRST
			add_action( 'init', array( $this, 'unified_clear_cache_handler' ) );

			// 2. LOADING/TIMING SECOND
			add_action( 'init', array( $this, 'start_page_load_time' ) );
			add_action( 'template_redirect', array( $this, 'load_cache_action_handler' ), 1 );

			// 3. GENERATING THIRD
			add_action( 'wp_loaded', array( $this, 'get_post_action_handler' ) );

			// 4. ADMIN UI
			add_action( 'admin_menu', array( $this, 'power_cache_menu' ) );
			add_action( 'admin_init', array( $this, 'power_cache_init' ) );
			add_action( 'admin_notices', array($this, 'wp_power_cache_admin_notice'));
			add_action( 'admin_bar_menu', array( $this, 'add_cache_id_to_admin_bar' ), 100 );
			add_filter( 'plugin_action_links_'.plugin_basename(__FILE__), array($this, 'add_wp_power_cache_settings_link'));
			add_action( 'wp_footer', array( $this, 'show_cache_clear_notice' ) );
			add_action( 'admin_head', array( $this, 'add_confirm_clear_js' ) );
		}

		private function FrontOrAdmin() {
			if ( is_admin() || is_user_logged_in() ) {
				$this->isAdmin = true;
			} else {
				$this->isFront = true;
			}
		}

		private function cache_exists() {
			$path = $this->cache_file_path();
			return ( file_exists( $path ) && filesize($path) > 0 ) ? $path : false;
		}

		private function cache_file_path() {
			// Sanitize the filename to prevent security issues with the file system
			$safe_name = sanitize_file_name( $this->currentCacheFile );
			return WRPC_ROOT_DIR . $this->cacheFolder . '/' . $safe_name . '.html';
		}

		private function create_cache( $buffer, $file_name = '' ) {
			if ( $file_name != "" ) {
				$this->currentCacheFile = $file_name;
			}
			if ( $this->isFront && ! $this->cache_exists() ) {
				$buffer = $this->sanitize_output( $buffer );
				file_put_contents( $this->cache_file_path(), $buffer );
			}
			return $buffer;
		}

		private function sanitize_output( $buffer ) {
			
			// We only want to remove extra spaces, NOT HTML comments
			$search  = array( '/\>[^\S ]+/s', '/[^\S ]+\</s', '/(\s)+/s' );
			$replace = array( '>', '<', '\\1' );
			return preg_replace( $search, $replace, $buffer );
		}
		
		public function power_cache_menu() {
			add_menu_page('WP Power Cache', 'WP Power Cache', 'manage_options', 'setting-power-cache', array($this, 'power_cache_setting_page'), 'dashicons-performance');
		}
		
		public function power_cache_init() {
			register_setting( 'wp-power-cache-group', 'wp_power_cache_settings' );
			$active_tab = $_GET['tab'] ?? 'debug_options';
			
			if( $active_tab == 'debug_options' ) {
				add_settings_section( 'developer_flag', __( 'Developer Mode', 'wp-power-cache' ), '__return_false', 'setting-power-cache' );
				add_settings_field( 'developer_flag_settings', __( 'Enable Developer Mode', 'wp-power-cache' ), array($this,'developer_flag_settings_callback'), 'setting-power-cache', 'developer_flag' );
				add_settings_field( 'debug_settings',          __( 'Debugging', 'wp-power-cache' ),             array($this,'debug_field_callback'),             'setting-power-cache','developer_flag');
			}
		}
		
		public function developer_flag_settings_callback() {
			$settings = (array) get_option( 'wp_power_cache_settings' );
			$val = $settings['developer_flag'] ?? 0;
			
			echo '<label class="wrpc-switch">';
			echo '<input type="checkbox" name="wp_power_cache_settings[developer_flag]" value="1"' . checked(1, $val, false) . '/>';
			echo '<span style="margin-left: 10px;">' . esc_html__( 'Enable Performance Monitoring Bar', 'wp-power-cache' ) . '</span>';
			echo '</label>';
			echo '<p class="description">' . esc_html__( 'Display exact page execution time at the top of your website for performance auditing.', 'wp-power-cache' ) . '</p>';
		}

		public function debug_field_callback() {
			$settings = (array) get_option( 'wp_power_cache_settings' );
			$val = $settings['debug_flag'] ?? 0;

			echo '<input type="checkbox" name="wp_power_cache_settings[debug_flag]" value="1"' . checked(1, $val, false) . '/>';
			echo '<span style="margin-left: 10px;">' . esc_html__( 'Append Cache Signature to HTML Source', 'wp-power-cache' ) . '</span>';
			
			echo '<div style="background: #f9f9f9; border: 1px solid #ccd0d4; padding: 12px; margin-top: 10px; border-radius: 4px; font-family: monospace; font-size: 12px; color: #666;">';
			//echo '&lt;!-- Your dynamic page generated in 0.0128 seconds. --&gt;<br>';
			echo '&lt;!-- This cached page generated by WP-Power-Cache on ' . date( "d-m-Y H:i:s" ) . ' --&gt;';
			echo '</div>';
		}
		
		public function power_cache_setting_page() {
			require_once plugin_dir_path( __FILE__ ) . 'power-cache-setting-page.php';
		}
		
		public function wp_power_cache_admin_notice() {
			if (isset($_GET['settings-updated'])) {
				settings_errors();
			}
		}
		
		public function add_wp_power_cache_settings_link( $links ) {
			$settings_link = '<a href="admin.php?page=setting-power-cache">' . __( 'Settings' ) . '</a>';
			array_unshift( $links, $settings_link );
			return $links;
		}

		public static function run() {
			if ( self::$instance == null ) {
				self::$instance = new self();
			}
			return self::$instance;
		}

		public function add_cache_id_to_admin_bar( $wp_admin_bar ) {
			if ( ! current_user_can( 'manage_options' ) || is_admin() ) {
				return;
			}

			$settings = (array) get_option( 'wp_power_cache_settings' );
			
			if ( isset($settings['debug_flag']) && $settings['debug_flag'] == 1 ) {
				$exists = $this->cache_exists();
				$status = $exists ? 'Cached' : 'Dynamic';
				$color  = $exists ? '#46b450' : '#ffb900';
				$total_size = $this->get_cache_size();
				
				// Main Status Node
				$wp_admin_bar->add_node( array(
					'id'    => 'wrpc-cache-status',
					'title' => '<span style="color:' . $color . ';">● WP Cache: ' . $status . '</span>',
					'href'  => admin_url( 'admin.php?page=setting-power-cache' ),
				) );

				// Sub-node: Show Total Cache Size
				$wp_admin_bar->add_node( array(
					'id'     => 'wrpc-cache-size',
					'parent' => 'wrpc-cache-status',
					'title'  => 'Total Size: ' . $total_size,
				) );

				// Sub-node: Clear THIS specific page
				if ( $exists ) {
					$wp_admin_bar->add_node( array(
						'id'     => 'wrpc-clear-this',
						'parent' => 'wrpc-cache-status',
						'title'  => 'Clear This Page Cache',
						'href'   => wp_nonce_url( add_query_arg( 'wrpc_clear_single', '1' ), 'wrpc_clear_single_action' ),
					) );
				}

				// NEW Sub-node: Empty ALL Cache
				$wp_admin_bar->add_node( array(
					'id'     => 'wrpc-empty-all',
					'parent' => 'wrpc-cache-status',
					'title'  => '<span style="color:#d63638;">Empty All Cache</span>',
					'href'   => wp_nonce_url( add_query_arg( 'wrpc_empty_all', '1' ), 'wrpc_empty_all_action' ),
					'meta'   => array(
						'onclick' => 'return confirm("Delete ALL cached files?");'
					),
				) );
			}
		}

		public function handle_single_clear_request() {
			// Check for the "Clear Single" trigger and security nonce
			if ( isset( $_GET['wrpc_clear_single'] ) && check_admin_referer( 'wrpc_clear_single_action' ) ) {
				
				// Ensure we have the current cache file name set
				if ( empty( $this->currentCacheFile ) ) {
					$this->currentCacheFile = $this->get_query_parameters( null );
				}

				$path = $this->cache_file_path();

				// Delete the file if it exists
				if ( file_exists( $path ) ) {
					unlink( $path );
				}

				// Redirect back to the clean URL
				wp_safe_redirect( add_query_arg( 'cache_cleared', '1', remove_query_arg( array( 'wrpc_clear_single', '_wpnonce' ) ) ) );
				exit;
			}
		}

		private function get_cache_size() {
			$size = 0;
			$directory = WRPC_ROOT_DIR . $this->cacheFolder;
			
			if ( ! is_dir( $directory ) ) return '0 B';

			foreach ( new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $directory ) ) as $file ) {
				if ( $file->isFile() ) {
					$size += $file->getSize();
				}
			}

			if ( $size === 0 ) return '0 B';

			$units = array( 'B', 'KB', 'MB', 'GB' );
			$power = $size > 0 ? floor( log( $size, 1024 ) ) : 0;
			return number_format( $size / pow( 1024, $power ), 2 ) . ' ' . $units[$power];
		}

		public function unified_clear_cache_handler() {

			// 1. GLOBAL CLEAR (All files)
			if ( (isset($_GET['wrpc_empty_all']) && check_admin_referer('wrpc_empty_all_action')) || isset($_POST['clear_all_cache']) ) {
				if ( isset($_POST['clear_all_cache']) ) {
					check_admin_referer( 'wrpc_clear_cache_action', 'wrpc_nonce' );
				}

				wrpc_recursive_dir_delete( WRPC_ROOT_DIR . $this->cacheFolder );

				if ( ! file_exists( WRPC_ROOT_DIR . $this->cacheFolder ) ) {
					wp_mkdir_p( WRPC_ROOT_DIR . $this->cacheFolder );
				}

				// Redirect with the 'all' flag
				wp_safe_redirect( add_query_arg( 'wrpc_cleared', 'all', remove_query_arg( array( 'wrpc_empty_all', '_wpnonce' ) ) ) );
				exit;
			}

			// 2. SINGLE PAGE CLEAR (One file)
			if ( isset( $_GET['wrpc_clear_single'] ) && check_admin_referer( 'wrpc_clear_single_action' ) ) {
				
				$filename = $this->get_standard_filename() . '.html';
				$path = WRPC_ROOT_DIR . $this->cacheFolder . '/' . $filename;

				if ( file_exists( $path ) ) {
					unlink( $path );
					// Redirect with the 'single' flag
					wp_safe_redirect( add_query_arg( 'wrpc_cleared', 'single', remove_query_arg( array( 'wrpc_clear_single', '_wpnonce' ) ) ) );
					exit;
				}
				
				// If file didn't exist, still redirect but without the success message
				wp_safe_redirect( remove_query_arg( array( 'wrpc_clear_single', '_wpnonce' ) ) );
				exit;
			}
		}

		private function get_standard_filename() {
			if ( is_front_page() || is_home() ) {
				return 'index';
			}

			// Standardize the URI by removing query strings and trailing slashes
			$uri = strtok($_SERVER['REQUEST_URI'], '?');
			$uri = rtrim($uri, '/');

			// If it's still empty after trimming, it's the homepage
			if ( empty($uri) ) {
				return 'index';
			}

			// Return the MD5 of the cleaned URI
			return md5( $uri );
		}

		public function show_cache_clear_notice() {
			if ( ! isset( $_GET['wrpc_cleared'] ) ) return;

			$type = $_GET['wrpc_cleared'];
			$message = '';
			$bg_color = '#46b450'; // Default Green

			if ( $type === 'all' ) {
				$message = '✓ Entire Website Cache Cleared';
				$bg_color = '#d63638'; // Red for global clear
			} elseif ( $type === 'single' ) {
				$message = '✓ Current Page Cache Cleared';
			}

			if ( $message ) {
				echo '<div id="wrpc-notice" style="position: fixed; top: 50px; right: 20px; z-index: 99999; background: ' . $bg_color . '; color: #fff; padding: 12px 24px; border-radius: 5px; box-shadow: 0 4px 15px rgba(0,0,0,0.3); font-family: -apple-system, BlinkMacSystemFont, sans-serif; font-weight: 500; animation: wrpc_fadeout 4s forwards;">';
				echo $message;
				echo '</div>';
				echo '<style>@keyframes wrpc_fadeout { 0% {opacity: 0; transform: translateY(-20px);} 10% {opacity: 1; transform: translateY(0);} 80% {opacity: 1;} 100% {opacity: 0; visibility: hidden;} }</style>';
			}
		}

		public function add_confirm_clear_js() {
			// Only output this on your plugin's settings page
			if ( isset($_GET['page']) && $_GET['page'] === 'setting-power-cache' ) {
				?>
				<script type="text/javascript">
					document.addEventListener('DOMContentLoaded', function() {
						// Target the button by its 'name' attribute
						const clearBtn = document.querySelector('input[name="clear_all_cache"]');
						if (clearBtn) {
							clearBtn.addEventListener('click', function(e) {
								if (!confirm('Are you sure you want to delete the entire cache folder? This action cannot be undone.')) {
									e.preventDefault(); // Stop the form from submitting
								}
							});
						}
					});
				</script>
				<?php
			}
		}

	}
	WR_Power_Cache::run();
endif;