<?php
/**
 * Plugin Name: WP Power Cache
 * Author: Milap Patel
 * Description: A simple Page/Post cache plugin.
 * Plugin URI: https://patelmilap.wordpress.com/
 * Author URI: https://youtube.com/c/codecanvas
 * Version: 0.1.0
 * Text Domain: wp-power-cache
 * Requires at least: 5.0
 * Requires PHP: 8.0
 */

if ( !defined( 'ABSPATH' ) ) exit;

require_once plugin_dir_path( __FILE__ ) . 'functions.php';
require_once plugin_dir_path( __FILE__ ) . 'wp-lazy-load.php';

if ( ! class_exists( 'WR_Power_Cache' ) ) :
	class WR_Power_Cache {
		private $cacheFolder = 'wp-power-cache';
		private $isFront = false;
		private $isAdmin = false;
		private $currentCacheFile = '';
		protected static $instance = null;
		protected static $startTime = 0;
		protected static $endTime = 0;
		private $isDev = false;
		private $actions = array(
			'clear_cache' => [
				'switch_theme',
				'comment_post',
				'permalink_structure_changed'
			]
		);

		public function __construct() {
			define( 'WRPC_ROOT_DIR', str_replace( '\\', '/', plugin_dir_path( __FILE__ ) ) );
			$this->cacheFolder = isset( $_SERVER['SERVER_NAME'] ) ? md5( $_SERVER['SERVER_NAME'] ) : $this->cacheFolder;
			
			$settings = (array) get_option( 'wp_power_cache_settings' );
			$this->isDev = isset($settings['developer_flag']) && $settings['developer_flag'] == 1;

			if ( ! file_exists( WRPC_ROOT_DIR . $this->cacheFolder ) ) {
				wp_mkdir_p( WRPC_ROOT_DIR . $this->cacheFolder );
				chmod( WRPC_ROOT_DIR . $this->cacheFolder, 0777 );
			}
			$this->add_actions();
		}

		public function get_post_action_handler( $q ) {
			if ( is_admin() ) return;

			// FIX: Get the filename first to check if it exists
			$this->currentCacheFile = $this->get_query_parameters( $q );

			// IF CACHE EXISTS: Do not start the buffer. 
			// This prevents the signature from being added a second time.
			if ( $this->cache_exists() && !is_user_logged_in() ) {
				return;
			}

			if ( $this->validCatchFile() ) {
				ob_start( array( $this, 'end_post_action_handler' ) );
			}
		}

		public function load_cache_action_handler() {
			$this->FrontOrAdmin();
			if ( $this->isFront && $this->cache_exists() ) {
				echo file_get_contents( $this->cache_file_path() );
				$this->end_page_load_time();
				exit;
			}
		}

		public function clear_cache_file( $post = null ) {
			// Security: Check nonce if this is called via the admin button
			if ( isset($_POST['clear_all_cache']) ) {
				check_admin_referer( 'wrpc_clear_cache_action', 'wrpc_nonce' );
			}

			if ( is_array($post) && isset( $post['post_name'] ) && $post['post_name'] != "" ) {
				$this->currentCacheFile = $post['post_name'];
				@unlink( $this->cache_file_path() );
			} else {
				wrpc_recursive_dir_delete( WRPC_ROOT_DIR . $this->cacheFolder );
			}
		}

		public function start_page_load_time() {
			self::$startTime = microtime( true );
		}

		public function end_page_load_time() {
			self::$endTime = microtime( true );
			$finish = round( ( self::$endTime - self::$startTime ), 4 );
			
			// Only show the black bar if Developer Mode is ON
			if ( $this->isDev ) {
				wrpc_print_loading_time( $finish );
			} 
		}

		public function end_post_action_handler( $buffer ) {
			if ( is_404() || empty($buffer) ) {
				return $buffer;
			}

			$settings = (array) get_option( 'wp_power_cache_settings' );
			
			if ( isset($settings['debug_flag']) && $settings['debug_flag'] == 1 ) {
				$finish = round( ( microtime(true) - self::$startTime ), 4 );
				
				//$signature  = "<!-- Your dynamic page generated in $finish seconds. -->\n";
				$signature .= "<!-- This cached page generated by WP-Power-Cache on ". date( "d-m-Y H:i:s" ) ." -->\n";
				
				$buffer .= $signature; 
			}

			return $this->create_cache( $buffer );
		}

		private function validCatchFile() {
			if ( empty($this->currentCacheFile) ) return false;
			$ext = pathinfo( $this->currentCacheFile, PATHINFO_EXTENSION );
			return !in_array( $ext, $this->invalid_file_extensions() );
		}

		private function invalid_file_extensions() {
			return array('gif', 'jpeg', 'jpg', 'png', 'swf', 'psd', 'bmp', 'tiff', 'ico');
		}

		private function get_query_parameters( $q ) {
			// 1. Check if it is the homepage
			if ( is_front_page() || is_home() ) {
				return 'index';
			}

			// 2. Try to get the unique slug from the queried object (Post, Page, or Category)
			$queried_object = get_queried_object();
			
			if ( isset( $queried_object->post_name ) ) {
				return $queried_object->post_name; // Returns the slug, e.g., 'about-us'
			} elseif ( isset( $queried_object->slug ) ) {
				return $queried_object->slug; // Returns category/tag slug
			}

			// 3. Fallback to a hash of the URL if no slug is found (for search results, etc.)
			return md5( $_SERVER['REQUEST_URI'] );
		}

		private function add_actions() {
			add_action( 'init', array( $this, 'start_page_load_time' ) );
			add_action( 'template_redirect', array( $this, 'load_cache_action_handler' ), 1 );
			add_action( 'wp_loaded', array( $this, 'get_post_action_handler' ) );
			add_action( 'admin_menu', array( $this, 'power_cache_menu' ) );
			add_action( 'admin_init', array( $this, 'power_cache_init' ) );
			add_action( 'admin_notices', array($this, 'wp_power_cache_admin_notice'));
			add_filter( 'plugin_action_links_'.plugin_basename(__FILE__), array($this, 'add_wp_power_cache_settings_link'));

			if ( isset($_POST['clear_all_cache']) ) {
				add_action( 'admin_init', array( $this, 'clear_cache_file' ) );
			}

			foreach ( $this->actions['clear_cache'] as $action ) {
				add_action( $action, array( $this, 'clear_cache_file' ) );
			}
		}

		private function FrontOrAdmin() {
			if ( is_admin() || is_user_logged_in() ) {
				$this->isAdmin = true;
			} else {
				$this->isFront = true;
			}
		}

		private function cache_exists() {
			$path = $this->cache_file_path();
			return ( file_exists( $path ) && filesize($path) > 0 ) ? $path : false;
		}

		private function cache_file_path() {
			// Sanitize the filename to prevent security issues with the file system
			$safe_name = sanitize_file_name( $this->currentCacheFile );
			return WRPC_ROOT_DIR . $this->cacheFolder . '/' . $safe_name . '.html';
		}

		private function create_cache( $buffer, $file_name = '' ) {
			if ( $file_name != "" ) {
				$this->currentCacheFile = $file_name;
			}
			if ( $this->isFront && ! $this->cache_exists() ) {
				$buffer = $this->sanitize_output( $buffer );
				file_put_contents( $this->cache_file_path(), $buffer );
			}
			return $buffer;
		}

		private function sanitize_output( $buffer ) {
			
			// We only want to remove extra spaces, NOT HTML comments
			$search  = array( '/\>[^\S ]+/s', '/[^\S ]+\</s', '/(\s)+/s' );
			$replace = array( '>', '<', '\\1' );
			return preg_replace( $search, $replace, $buffer );
		}
		
		public function power_cache_menu() {
			add_menu_page('WP Power Cache', 'WP Power Cache', 'manage_options', 'setting-power-cache', array($this, 'power_cache_setting_page'), 'dashicons-performance');
		}
		
		public function power_cache_init() {
			register_setting( 'wp-power-cache-group', 'wp_power_cache_settings' );
			$active_tab = $_GET['tab'] ?? 'debug_options';
			
			if( $active_tab == 'debug_options' ) {
				add_settings_section( 'developer_flag', __( 'Developer Mode', 'wp-power-cache' ), '__return_false', 'setting-power-cache' );
				add_settings_field( 'developer_flag_settings', __( 'Enable Developer Mode', 'wp-power-cache' ), array($this,'developer_flag_settings_callback'), 'setting-power-cache', 'developer_flag' );
				add_settings_field( 'debug_settings',          __( 'Debugging', 'wp-power-cache' ),             array($this,'debug_field_callback'),             'setting-power-cache','developer_flag');
			}
		}
		
		public function developer_flag_settings_callback() {
			$settings = (array) get_option( 'wp_power_cache_settings' );
			$val = $settings['developer_flag'] ?? 0;
			
			echo '<label class="wrpc-switch">';
			echo '<input type="checkbox" name="wp_power_cache_settings[developer_flag]" value="1"' . checked(1, $val, false) . '/>';
			echo '<span style="margin-left: 10px;">' . esc_html__( 'Enable Performance Monitoring Bar', 'wp-power-cache' ) . '</span>';
			echo '</label>';
			echo '<p class="description">' . esc_html__( 'Display exact page execution time at the top of your website for performance auditing.', 'wp-power-cache' ) . '</p>';
		}

		public function debug_field_callback() {
			$settings = (array) get_option( 'wp_power_cache_settings' );
			$val = $settings['debug_flag'] ?? 0;

			echo '<input type="checkbox" name="wp_power_cache_settings[debug_flag]" value="1"' . checked(1, $val, false) . '/>';
			echo '<span style="margin-left: 10px;">' . esc_html__( 'Append Cache Signature to HTML Source', 'wp-power-cache' ) . '</span>';
			
			echo '<div style="background: #f9f9f9; border: 1px solid #ccd0d4; padding: 12px; margin-top: 10px; border-radius: 4px; font-family: monospace; font-size: 12px; color: #666;">';
			//echo '&lt;!-- Your dynamic page generated in 0.0128 seconds. --&gt;<br>';
			echo '&lt;!-- This cached page generated by WP-Power-Cache on ' . date( "d-m-Y H:i:s" ) . ' --&gt;';
			echo '</div>';
		}
		
		public function power_cache_setting_page() {
			require_once plugin_dir_path( __FILE__ ) . 'power-cache-setting-page.php';
		}
		
		public function wp_power_cache_admin_notice() {
			if (isset($_GET['settings-updated'])) {
				settings_errors();
			}
		}
		
		public function add_wp_power_cache_settings_link( $links ) {
			$settings_link = '<a href="admin.php?page=setting-power-cache">' . __( 'Settings' ) . '</a>';
			array_unshift( $links, $settings_link );
			return $links;
		}

		public static function run() {
			if ( self::$instance == null ) {
				self::$instance = new self();
			}
			return self::$instance;
		}
	}
	WR_Power_Cache::run();
endif;